import localFont from 'next/font/local';
import './globals.css';
import { Metadata } from 'next';


const iransans  = localFont({
  src: '../public/iransans/woff2/iransans-Black.woff2', 
  variable: '--font-iransans', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${iransans.variable} ${iransans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
